name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build static wyam website
      run: |
        dotnet tool install -g Wyam.Tool
        ~/.dotnet/tools/wyam -o wwwroot
    - name: copy static web.config 
        run: |
        cp web.config.static wwwroot/web.config
    - name: Upload static website
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: static website
        # Directory containing files to upload
        path: wwwroot

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: LynsiWebside
        package: wwwroot

