name: .NET Core

on: [push]


env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '2.2.402'      

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build with dotnet
      run: |
        dotnet tool install -g Wyam.Tool
        ~/.dotnet/tools/wyam -o wwwroot
    - name: Upload static website
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: static website
        # Directory containing files to upload
        path: wwwroot

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: LynsiWebside
        package: lynsy